days_to_crawl: 1000
loop_interval_for_new_keyword_accepted: 2
maximum_topic_display_length: 20
crawling_list:
- Tinhte:
    id_type: href
    browser_profile: ''
    web_url: https://tinhte.vn/
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: //div[contains(@class,'comment__attachments')] | //div[contains(@class,'comment__attachments')]/following-sibling::*
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //meta[@name='description']/@content
    - //meta[@name='description']/@content
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: false
    last_run: 30/01/2021 02:20
    contain: ''
    crawl_url: https://tinhte.vn/
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //div[@class="datePublished"]
    - //div[@class="datePublished"]
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[contains(@class, "content-wrapper")]
    - //div[contains(@class, "content-wrapper")]
    text_xpath:
    - .//div[@data-author]
    image_box_xpath:
    - .//img
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://tinhte.vn/
    minimum_topic_length: 4
    tags: []
    remove_me: false
- Cafebiz:
    id_type: href
    browser_profile: ''
    web_url: http://cafebiz.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - //node()[contains(@class, "link-content-footer")]
    - //node()[@id="admzone480459"]
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //node()[@class="sapo"]
    - //node()[@class="sapo"]
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 30/01/2021 02:20
    contain: ''
    crawl_url: http://cafebiz.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class="timeandcatdetail"]/node()[@class="time"]
    - //node()[@class="timeandcatdetail"]/node()[@class="time"]
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //node()[@class="w640right"]
    - //node()[@class="w640right"]
    text_xpath:
    - ./node()[@class="detail-content"]/p
    image_box_xpath:
    - //*[@id="mainDetail"]//center
    - .//node()[@type="Photo"]
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://cafebiz.vn
    minimum_topic_length: 4
    tags: []
    only_quality_post: true
    browser_timeout: 60
    prevent_auto_redirect: false
    remove_me: false
- Codeaholicguy:
    id_type: href
    browser_profile: ''
    web_url: https://codeaholicguy.com/
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //meta[@property='og:description']/@content
    - //meta[@property='og:description']/@content
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 30/01/2021 02:20
    contain: ''
    crawl_url: https://codeaholicguy.com/
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //time[@class='entry-date published']/@datetime
    - //time[@class='entry-date published']/@datetime
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[@class='site-content']
    - //div[@class='site-content']
    text_xpath:
    - .//p
    - .//h2
    - .//h3
    - .//h4
    image_box_xpath:
    - .//img
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://codeaholicguy.com/
    minimum_topic_length: 4
    tags: []
    remove_me: false
- vuilaptrinh.com:
    id_type: href
    browser_profile: ''
    web_url: http://vuilaptrinh.com/
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img[1]/@src
    - .//img[1]/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //meta[@name='description']/@content
    - //meta[@name='description']/@content
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 30/01/2021 02:20
    contain: ''
    crawl_url: http://vuilaptrinh.com/
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //meta[@property='og:url']/@content
    - //meta[@property='og:url']/@content
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[@class='blog-post']
    - //div[@class='blog-post']
    text_xpath:
    - .//p
    - .//h2
    - .//h3
    - .//h4
    image_box_xpath:
    - .//img
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://vuilaptrinh.com/
    minimum_topic_length: 4
    tags: []
    remove_me: false
    only_quality_post: false
- topdev.vn:
    id_type: href
    browser_profile: ''
    web_url: https://topdev.vn/blog/
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths:
    - (//strong[contains(text(),'Có thể bạn quan tâm:')]/..)/following::*
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img[1]/@src
    - .//img[1]/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //meta[@property='og:description']/@content
    - //meta[@property='og:description']/@content
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 30/01/2021 02:20
    contain: ''
    crawl_url: https://topdev.vn/blog/
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //meta[@property='article:published_time']/@content
    - //meta[@property='article:published_time']/@content
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[contains(@class, 'td-post-content')]
    - //div[contains(@class, 'td-post-content')]
    text_xpath:
    - .//p
    - .//li
    image_box_xpath:
    - .//img
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://topdev.vn/blog/
    minimum_topic_length: 4
    tags: []
    remove_me: false
    only_quality_post: false
- Nam Vo 's Blog:
    id_type: href
    browser_profile: ''
    web_url: https://vhnam.github.io
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img[1]/@src
    - .//img[1]/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //meta[@itemprop='mainEntityOfPage']/@content
    - //meta[@itemprop='mainEntityOfPage']/@content
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: true
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 30/01/2021 02:20
    contain: ''
    crawl_url: https://vhnam.github.io
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //meta[@itemprop='datePublished']/@content
    - //meta[@itemprop='datePublished']/@content
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[@class='content__heading']/..
    - //div[@class='content__heading']/..
    text_xpath:
    - .//p
    image_box_xpath:
    - .//img
    image_title_xpath:
    - .//img/@alt
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://vhnam.github.io
    minimum_topic_length: 2
    tags: []
    only_quality_post: false
    browser_timeout: 60
    prevent_auto_redirect: false
    remove_me: false
- Viblo:
    id_type: href
    browser_profile: ''
    web_url: https://viblo.asia
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img[1]/@src
    - .//img[1]/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //meta[@name='description']/@content
    - //meta[@name='description']/@content
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: true
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 30/01/2021 02:20
    contain: ''
    crawl_url: https://viblo.asia/newest
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //meta[contains(@name, 'modified_time')]/@content
    - //meta[contains(@name, 'modified_time')]/@content
    topic_type: href
    maximum_url: 30
    get_detail_content: true
    content_xpath:
    - //div[contains(@class, 'article-content')]
    - //div[contains(@class, 'article-content')]
    text_xpath:
    - .//p
    - .//h2
    - .//h3
    - .//h4
    image_box_xpath:
    - //img
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://viblo.asia
    minimum_topic_length: 4
    tags: []
    only_quality_post: false
    browser_timeout: 60
    prevent_auto_redirect: false
    remove_me: false
- genk:
    id_type: href
    browser_profile: ''
    web_url: http://genk.vn
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img/@src
    - .//img/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //h2[@class='knc-sapo'] | //meta[@property='og:description']/@content
    - //h2[@class='knc-sapo'] | //meta[@property='og:description']/@content
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 30/01/2021 02:20
    contain: ''
    crawl_url: http://genk.vn
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //node()[@class="kbwcm-time"]/@title | //meta[@itemprop="datePublished"]/@content
    - //node()[@class="kbwcm-time"]/@title | //meta[@itemprop="datePublished"]/@content
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[contains(@class, 'new-content') or contains(@class, 'body-content')]
    - //div[contains(@class, 'new-content') or contains(@class, 'body-content')]
    text_xpath:
    - .//p
    image_box_xpath:
    - .//img
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: http://genk.vn
    minimum_topic_length: 4
    tags: []
    only_quality_post: false
    browser_timeout: 60
    prevent_auto_redirect: false
    remove_me: false
- Toidicodedao:
    id_type: href
    browser_profile: ''
    web_url: https://toidicodedao.com/
    timezone: Asia/Ho_Chi_Minh
    remove_date_tag_html: false
    remove_content_html: true
    use_index_number: false
    remove_content_html_xpaths: []
    minimum_duration_between_crawls: 15
    language: vietnamese
    feature_image_xpath:
    - .//img[1]/@src
    - .//img[1]/@src
    extract_xpath:
    - ./text()
    - ./@title
    topics_xpath:
    - //a[text()]
    - //a[@title]
    skip_checking_topic_length: false
    display_browser: false
    sapo_xpath:
    - //h1[@class='entry-title']
    - //h1[@class='entry-title']
    get_publish_date_as_crawl_date: false
    browser_fast_load: true
    skip_repeat_topic: true
    use_browser: false
    date_place: detail_page
    ignore_topic_not_have_publish_date: true
    last_run: 30/01/2021 02:20
    contain: ''
    crawl_url: https://toidicodedao.com/
    output_html: false
    get_topic_from_link: true
    date_xpath:
    - //time[@class='entry-date']/@datetime
    - //time[@class='entry-date']/@datetime
    topic_type: href
    maximum_url: 10
    get_detail_content: true
    content_xpath:
    - //div[@class='entry-content']
    - //div[@class='entry-content']
    text_xpath:
    - .//p
    - .//ul
    - .//li
    image_box_xpath:
    - .//img
    image_title_xpath: []
    video_box_xpath: []
    video_title_xpath: []
    audio_box_xpath: []
    audio_title_xpath: []
    avatar_type: url
    avatar_url: ''
    avatar_xpath: ''
    crawl_type: newspaper
    url_pattern_re: https://toidicodedao.com/
    minimum_topic_length: 4
    tags: []
    remove_me: false
running_path: ~/docbao_crawler/
number_of_trending_keywords: 25
number_of_hot_keywords: 2000
minimum_topic_length: 4
display_timezone: Asia/Ho_Chi_Minh
hub_href: ''
minimum_keyword_length_for_fast_growing_keyword_accepted: 2
crawling_interval: 15
minimum_freq_for_more_than_two_length_keyword_appear_in_hot_keywords: 5
minimum_freq_series_for_fast_growing_keyword_accepted: 2
max_crawler: 5
category_list:
- chính trị:
    index: 1
    filename: category/chinh_tri.txt
- Kinh Tế:
    index: 2
    filename: category/kinh_te.txt
- Xã Hội:
    index: 3
    filename: category/xa_hoi.txt
- An Ninh:
    index: 4
    filename: category/an_ninh.txt
- Quốc Phòng:
    index: 5
    filename: category/quoc_phong.txt
- Văn Hoá:
    index: 6
    filename: category/van_hoa.txt
- Giáo Dục:
    index: 7
    filename: category/giao_duc.txt
- Thể Thao:
    index: 8
    filename: category/the_thao.txt
- Giải Trí:
    index: 9
    filename: category/giai_tri.txt
- Công nghệ:
    index: 10
    filename: category/cong_nghe.txt
- Giao Thông:
    index: 11
    filename: category/giao_thong.txt
- Quốc gia:
    index: 12
    filename: category/quoc_gia.txt
- Địa danh:
    index: 13
    filename: category/dia_danh.txt
- Sự kiện:
    index: 14
    filename: category/su_kien.txt
- Nhân vật:
    index: 15
    filename: category/nhan_vat.txt
use_CDN: true
waiting_time_between_each_crawl: 3
trending_duration: 720
minimum_publish_speed: 600
minimum_freq_for_two_length_keyword_appear_in_hot_keywords: 2
maximum_url_to_visit_each_turn: 15
minimum_weight: 0.002
timeout: 500
hub_title: Theo Dõi Tin Tức Mùa Thi THPT Quốc gia 2019
minimum_freq_for_new_keyword_accepted: 1
mininum_freq_for_new_keyword_accepted: 1
minimum_freq_for_fast_growing_keyword_accepted: 3
