version: '3.4'

services:
  crawler-topdup:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    networks: 
      - crawler-system
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    networks: 
      - crawler-system
    restart: on-failure
      
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "6787:80"
    env_file:
      - pgadmin.env
    networks: 
      - crawler-system
    restart: on-failure

networks: 
  crawler-system: