# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v2
      # https://github.com/actions/cache/blob/main/examples.md#python---pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 .

    - name: Check type annotations with mypy
      run: |
        mypy ./modules/ml*/*.py

    - name: Test with pytest
      run: |
        python3 -m pytest -s --durations=0 --cov=./ --cov-report=xml modules/ml/tests/

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
        directory: ./coverage/reports/
        flags: pytest
        env_vars: OS,PYTHON
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
